security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
    access_control:
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/me, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/stations, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/trains, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/horaires, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/trajets, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/favoris, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/notifications, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/horaires-conducteurs/mon-planning, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/maintenances, roles: IS_AUTHENTICATED_FULLY, methods: [GET] }
        - { path: ^/api/maintenances, roles: IS_AUTHENTICATED_FULLY, methods: [PUT] }
        - { path: ^/api, roles: ROLE_ADMIN }
