<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260710120809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE horaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, heure_depart TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_arrivee TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, jours VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, train_id INT NOT NULL, trajet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BBC83DB623BCD4D0 ON horaire (train_id)');
        $this->addSql('CREATE INDEX IDX_BBC83DB6D12A823 ON horaire (trajet_id)');
        $this->addSql('CREATE TABLE modification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_modif TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ancienne_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, nouvelle_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, motif VARCHAR(255) DEFAULT NULL, type VARCHAR(50) NOT NULL, horaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF6425D258C54515 ON modification (horaire_id)');
        $this->addSql('CREATE TABLE station (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, ville VARCHAR(100) NOT NULL, address VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE train (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, capacite INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE trajet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, distance_km DOUBLE PRECISION NOT NULL, station_depart_id INT NOT NULL, station_arrivee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B5BA98C2C869050 ON trajet (station_depart_id)');
        $this->addSql('CREATE INDEX IDX_2B5BA98C601733C0 ON trajet (station_arrivee_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE horaire ADD CONSTRAINT FK_BBC83DB623BCD4D0 FOREIGN KEY (train_id) REFERENCES train (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horaire ADD CONSTRAINT FK_BBC83DB6D12A823 FOREIGN KEY (trajet_id) REFERENCES trajet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE modification ADD CONSTRAINT FK_EF6425D258C54515 FOREIGN KEY (horaire_id) REFERENCES horaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98C2C869050 FOREIGN KEY (station_depart_id) REFERENCES station (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98C601733C0 FOREIGN KEY (station_arrivee_id) REFERENCES station (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE horaire DROP CONSTRAINT FK_BBC83DB623BCD4D0');
        $this->addSql('ALTER TABLE horaire DROP CONSTRAINT FK_BBC83DB6D12A823');
        $this->addSql('ALTER TABLE modification DROP CONSTRAINT FK_EF6425D258C54515');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98C2C869050');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98C601733C0');
        $this->addSql('DROP TABLE horaire');
        $this->addSql('DROP TABLE modification');
        $this->addSql('DROP TABLE station');
        $this->addSql('DROP TABLE train');
        $this->addSql('DROP TABLE trajet');
        $this->addSql('DROP TABLE "user"');
    }
}
