<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260716151426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE favori (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_ajout TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, voyageur_id INT NOT NULL, horaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF85A2CC62915402 ON favori (voyageur_id)');
        $this->addSql('CREATE INDEX IDX_EF85A2CC58C54515 ON favori (horaire_id)');
        $this->addSql('CREATE TABLE horaire_conducteur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, conducteur_id INT NOT NULL, horaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E29C57D2F16F4AC6 ON horaire_conducteur (conducteur_id)');
        $this->addSql('CREATE INDEX IDX_E29C57D258C54515 ON horaire_conducteur (horaire_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, lu BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, voyageur_id INT NOT NULL, horaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA62915402 ON notification (voyageur_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA58C54515 ON notification (horaire_id)');
        $this->addSql('ALTER TABLE favori ADD CONSTRAINT FK_EF85A2CC62915402 FOREIGN KEY (voyageur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favori ADD CONSTRAINT FK_EF85A2CC58C54515 FOREIGN KEY (horaire_id) REFERENCES horaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horaire_conducteur ADD CONSTRAINT FK_E29C57D2F16F4AC6 FOREIGN KEY (conducteur_id) REFERENCES personnel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE horaire_conducteur ADD CONSTRAINT FK_E29C57D258C54515 FOREIGN KEY (horaire_id) REFERENCES horaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA62915402 FOREIGN KEY (voyageur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA58C54515 FOREIGN KEY (horaire_id) REFERENCES horaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT fk_42c8495558c54515');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT fk_42c8495562915402');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('ALTER TABLE horaire ADD retard_minutes INT DEFAULT NULL');
        $this->addSql('ALTER TABLE personnel ADD compte_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE personnel ADD CONSTRAINT FK_A6BCF3DEF2C56620 FOREIGN KEY (compte_id) REFERENCES "user" (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6BCF3DEF2C56620 ON personnel (compte_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_reservation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(50) NOT NULL, places_reservees INT NOT NULL, voyageur_id INT NOT NULL, horaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_42c8495558c54515 ON reservation (horaire_id)');
        $this->addSql('CREATE INDEX idx_42c8495562915402 ON reservation (voyageur_id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_42c8495558c54515 FOREIGN KEY (horaire_id) REFERENCES horaire (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT fk_42c8495562915402 FOREIGN KEY (voyageur_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE favori DROP CONSTRAINT FK_EF85A2CC62915402');
        $this->addSql('ALTER TABLE favori DROP CONSTRAINT FK_EF85A2CC58C54515');
        $this->addSql('ALTER TABLE horaire_conducteur DROP CONSTRAINT FK_E29C57D2F16F4AC6');
        $this->addSql('ALTER TABLE horaire_conducteur DROP CONSTRAINT FK_E29C57D258C54515');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA62915402');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA58C54515');
        $this->addSql('DROP TABLE favori');
        $this->addSql('DROP TABLE horaire_conducteur');
        $this->addSql('DROP TABLE notification');
        $this->addSql('ALTER TABLE horaire DROP retard_minutes');
        $this->addSql('ALTER TABLE personnel DROP CONSTRAINT FK_A6BCF3DEF2C56620');
        $this->addSql('DROP INDEX UNIQ_A6BCF3DEF2C56620');
        $this->addSql('ALTER TABLE personnel DROP compte_id');
    }
}
