<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260715213018 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE maintenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, train_id INT NOT NULL, personnel_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F84F8E923BCD4D0 ON maintenance (train_id)');
        $this->addSql('CREATE INDEX IDX_2F84F8E91C109075 ON maintenance (personnel_id)');
        $this->addSql('CREATE TABLE personnel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, tlf VARCHAR(20) DEFAULT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_reservation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(50) NOT NULL, places_reservees INT NOT NULL, voyageur_id INT NOT NULL, horaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C8495562915402 ON reservation (voyageur_id)');
        $this->addSql('CREATE INDEX IDX_42C8495558C54515 ON reservation (horaire_id)');
        $this->addSql('ALTER TABLE maintenance ADD CONSTRAINT FK_2F84F8E923BCD4D0 FOREIGN KEY (train_id) REFERENCES train (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE maintenance ADD CONSTRAINT FK_2F84F8E91C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495562915402 FOREIGN KEY (voyageur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495558C54515 FOREIGN KEY (horaire_id) REFERENCES horaire (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE maintenance DROP CONSTRAINT FK_2F84F8E923BCD4D0');
        $this->addSql('ALTER TABLE maintenance DROP CONSTRAINT FK_2F84F8E91C109075');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495562915402');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495558C54515');
        $this->addSql('DROP TABLE maintenance');
        $this->addSql('DROP TABLE personnel');
        $this->addSql('DROP TABLE reservation');
    }
}
