<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260806081846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ligne_station (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre INT NOT NULL, distance_depuis_debut DOUBLE PRECISION DEFAULT NULL, ligne_id INT NOT NULL, station_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0C6885A438E76 ON ligne_station (ligne_id)');
        $this->addSql('CREATE INDEX IDX_A0C68821BDB235 ON ligne_station (station_id)');
        $this->addSql('ALTER TABLE ligne_station ADD CONSTRAINT FK_A0C6885A438E76 FOREIGN KEY (ligne_id) REFERENCES ligne (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_station ADD CONSTRAINT FK_A0C68821BDB235 FOREIGN KEY (station_id) REFERENCES station (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trajet ADD ligne_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98C5A438E76 FOREIGN KEY (ligne_id) REFERENCES ligne (id)');
        $this->addSql('CREATE INDEX IDX_2B5BA98C5A438E76 ON trajet (ligne_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ligne_station DROP CONSTRAINT FK_A0C6885A438E76');
        $this->addSql('ALTER TABLE ligne_station DROP CONSTRAINT FK_A0C68821BDB235');
        $this->addSql('DROP TABLE ligne');
        $this->addSql('DROP TABLE ligne_station');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98C5A438E76');
        $this->addSql('DROP INDEX IDX_2B5BA98C5A438E76');
        $this->addSql('ALTER TABLE trajet DROP ligne_id');
    }
}
